name: New Task
description: Create a new task to be worked on
title: ''
labels: ''
assignees: ''
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the task.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: A list of criteria that must be met for the task to be considered complete.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
